name: MCONE-BuildSystem
author: Rufus Maiwald
version: 1.0.1-SNAPSHOT
main: eu.mcone.buildsystem.Main
depend: [MCONE-BukkitCoreSystem]
softdepend: [WorldEdit]

commands:
  spawn:
    description: Teleportiert den Spieler zum Spawn
  holo:
    description: Setze die einzelnen Hologramme
    permission: system.bukkit.holo
  tpa:
    description: Schickt eine Teleportanfrage
  tpaccept:
    description: Akzeptiert eine Teleportanfrage
  tpdeny:
    description: Verweigert eine Teleportanfrage
  skull:
    description: Gibt den Kopf eines Spielers
    permission: build.skull

permissions:
  build:
    description: Lobby Main Permission
    children:
      build.set:
        description: Allows to set several things
        children:
          build.set.spawn:
            description: Allows to set the spawn
      build.skull:
        description: Allows to get a players skull