name: MCONE-BuildSystem
author: Rufus Maiwald
version: ${project.version}
main: eu.mcone.buildsystem.BuildSystem
depend: [MCONE-BukkitCoreSystem]
softdepend: [WorldEdit,FastAsyncWorldEdit]
permissions:
  build:
    description: Build Main Permission
    children:
      build.skull:
        description: Allows to get a players skull